### PR TITLE
Consolidate to one package and update

### LINKED ISSUE #38: Move to top level package.json instead of build.sh
To be more consistent with our other packages, I think we should move to a top-level package.json that cd's into the subdirs and builds the subpackages (instead of the build.sh). This will be more familiar to our other devs and we can have separate npm commands for each subpackage.

@gnestor

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #60.  Fixes #38.

- Switches to a single top level npm package.
- Uses `data_files` to ship the extensions
- General cleanup

### CODE REVIEW

**Comment by blink1073** [comment]
Once this goes it we can update https://github.com/jupyterlab/mimerender-cookiecutter-ts with similar content.

**Comment by gnestor** [comment]
Thanks for tackling this, @blink1073!! It looks good to me except that after discussing with @ellisonbg a while back, the plan was to create *wrapper* (for lack of a better term) that could easily consume a renderer labextension and return a nbextension. Ideally, it would be a npm package that can be added as a devDependency to this cookiecutter and used as a build step (e.g. `npm run build:nbextension`. 

So, to think through this, when `npm run build:nbextension` is run, the library will:

* Create an `/nbextension` directory and copy a `setup.py`, `setupbase.by`, `MANIFEST.in`, Python package sub-directory withh `__init__.py` and `_version.py`.
* Create a temporary directory with an `index.js` that imports the mime type and widget from `/src/index` (the labextension) and exports `load_ipython_extension` (which will handle all of the wiring that is currently handled in `extension.js` and `renderer.js`).
* Run `webpack` and output the bundle to `/nbextension/static`.

The result is–from the extension author's point of view–a simple node module with a single `src/index.js` file that is a phosphor widget and `npm run build:labextension` and `npm run build:nbextension` scripts that build the labextension and nbextension, respectively (or `npm run build` which runs both).

The one downside to this approach is that it abstracts away the nbextension and it in turn makes it difficult to modify. However, that's also what the `IRenderMime.IExtension` does for labextensions: it abstracts away much of the labextension in favor of a simple interface for rendering outputs/documents. 

What are your thoughts?

**Comment by blink1073** [comment]
Yeah, that seems fair.  We can use the files in this PR as the template for that other package, similar JupyterLab's [create:package](https://github.com/jupyterlab/jupyterlab/blob/8999530fce9317fe3b2cafe60671c70bcebb32f1/buildutils/src/create-package.ts).

**Comment by gnestor** [comment]
I'm ok with merging this in the meantime because it seems like it could take some time

**Comment by blink1073** [comment]
Yeah, that sounds good.

**Review by gnestor — APPROVED** [review]

**Comment by gnestor** [comment]
I haven't had a chance to test, but is it working for you? Do you want me to test locally before merging?

**Comment by blink1073** [comment]
I've tested it locally and there are some solid tests on Travis (not yet selenium because of that bug).  Iterating we go.

**Pull request merged**
