### PR TITLE
Update the lab extension

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
@jasongrout, this is ready for review, as a basis for the fasta demo.

**Comment by cjh1** [comment]
It would be great if we could preserve the support for JavaScript, I have couple of plugins using this.

**Comment by blink1073** [comment]
Hi @cjh1, we are trying to encourage best practices by using TypeScript, having found it a great aid in making JupyterLab itself.

**Comment by cjh1** [comment]
@blink1073 Sure, I can understand that. Its just a bit of a stretch to convert to TypeScript when all we want to do it upgrade to the latest JupyterLab :smile:

**Comment by blink1073** [comment]
Closing in favor of #64

**Pull request closed without merging**
